### PR TITLE
Add additional column name support to user uploaded catalogs

### PR DESCRIPTION
**Pull request by ziyaointl**
In case `ra` and `dec` columns are not found, attempt to find and rename `TARGET_RA` and `TARGET_DEC` to `ra` and `dec`.

### CODE REVIEW

**Comment by dstndstn** [comment]
What time zone are you in?!  :)

Great idea -- thank you!  I will merge this to the "dev" version of the viewer immediately.
( http://legacysurvey.org/viewer-dev )

cheers,
--dustin

**Comment by ziyaointl** [comment]
Technically Pacific Daylight Time. I just turned out to have an unusual sleep schedule ;) Thanks for merging!

**Comment by sbailey** [comment]
For context, this was motivated by our fiberassign tile files using "TARGET_RA" and "TARGET_DEC".  This PR lets us directly upload a tile file to view the targets.  Thanks @ziyaointl .

**Comment by dstndstn** [comment]
Yep, that's what I guessed was going on -- thanks to @ziyaointl for taking
the initiative to make it work right!

**Pull request merged**
