### PR TITLE
Add fiber projections in DESI footprint

### PR DESCRIPTION
**Pull request by ziyaointl**
A video demonstration may be found here:
https://youtu.be/tVqUPWe0AQA

Main changes:
1. Added data for fiber locations
2. Implemented fiber location transformations from xyz to radec
3. Implemented visualization for fiber locations
4. Updated data for gfa corner positions

### CODE REVIEW

**Comment by dstndstn** [comment]
This looks great!

A few comments and questions.

In getFiberMultiLatLngs, it looks like you're calling xyz2radec for each of the 5,000 fibers, so constructing the rotation matrices 5,000 times and then applying them to 20 points.  Would it be possible to refactor this to do all the rotations at once?

In data.js, it looks like you have rendered out each fiber's projection on the unit sphere at 20 points around the fiber radius.  Is this really necessary?  This file is 6 MB -- fairly big...  If you had the center and radial and tangential radius of each fiber, you could make this considerably smaller, and maybe also make the math much faster (using ellipses rather than polylines).

Also, could you please rename data.js to something more specific -- desi-fiber-locations.js or something like that?

Thanks!  Nice work!

**Comment by ziyaointl** [comment]
Thanks for your suggestions!

After taking another look at the code, I think it would be possible to transform all the points at once. Although we would have to split them into their respective polylines after the transformation, I guess this could still noticeably improve performance. I will go ahead and make the changes.

In my first few attempts I did try plotting the ellipses directly, but I didn't figure out the right way to accurately transform those ellipses once telra, teldec moved to another location. So we decided to transform points instead and see if the performance holds up. Turns out, the performance is acceptable. The downside of this approach as you've mentioned is that the data file can get quite large, but since only the people clicking on the desi footprint option would have to load this file, so I guess this is also acceptable? Please let me know about what you think!

Renaming data.js is also a good idea. I will commit this change right away.

Thank you again for your suggestions!

**Comment by sbailey** [comment]
Chiming in: indeed, the fibers projected onto the sky are ellipses (well, almost), but by the time we plot them in 2D RA/dec space as-if those were orthogonal cartesian axes, they aren't ellipses anymore and the difference is visible by eye, and so we punted to the 20x points and a gadzillion transforms.

The file could be made smaller by storing 500 fibers and then rotating 10x times in 2D before doing the full 3D rotations to the final RA,dec, but that might further slow down the load.

We've worked out an alternative ellipse approximation that is more accurate than naive ellipses but not quite these 20x5000 points either, but we thought we'd float this option as a potentially good-enough-to-be-useful solution.  @ziyaointl did do some nifty tricks to do the fiber transforms in a separate thread so that it isn't a UI-blocking action.

Also note that showing the fibers is purposefully and automatically zoom-level dependent (i.e. only display them when zoomed in far enough that they are meaningful).

**Comment by ziyaointl** [comment]
I just refactored the code to transform all the points at once. Time improvement ranges from modest to 50%, so I guess that was worthwhile. Thanks for bringing this up!

**Comment by dstndstn** [comment]
Sorry for the delay -- there one more thing I'm wondering.

Currently you've added this to the DESI Footprint layer, right?  I'm wondering if we want to make the DESI Fibers a separate layer that can be toggled independently.  I think the DESI Footprint layer will be somewhat useful during the DESI Commissioning, for example, and there they won't want to see the fiber outlines.

Thanks again for this great work -- it's really impressive!

**Comment by ziyaointl** [comment]
No worries! Yes, you are right - the fiber location projections are currently part of the DESI Footprint layer. Stephen and I decided to make the projections automatically show/hide based zoom level so that the user won't have to manually toggle them, though I imagine adding them as a separate layer is certainly doable. For now, let's see what @sbailey thinks.

Thanks for your approval! It was definitely a fun feature to work on.

**Comment by sbailey** [comment]
@dstndstn we had thought about whether the fibers should be on a separate layer or not, and I was on the fence mainly because there are N>>1 layer options already. But I agree that ideally we could toggle the fibers separately from the rest of the footprint, so let's go to N+1 layers and add that as a separate button.

@dstndstn would you like to wait until we chat in person next week about ellipse math before merging this PR, or is the brute force 20x5000 points good enough for now (after organizing them as a separate layer)?

**Comment by dstndstn** [comment]
I'm totally happy merging this with your current approach -- if we can make it run faster (or make the data file much smaller) via some ellipse math, then that's great, but no need to hold up this work -- better to keep up the velocity and motivation!

With the way you have handled turning on the fibers at different scales -- clever -- it may turn out that we end up making it one layer again, but I think I would appreciate the chance to test them separately.

**Comment by djschlegel** [comment]
Dustin-- If there's a straightforward way of having some of the layers "turn off" when one zooms out too far, that would be convenient for many of the other layers (targets, SDSS spectra, GAIA, ...).  We could define the zoom layer at which any layer is disabled.  This would make it more convenient to zoom out, drive around the sky, and then zoom back in for target catalogs, etc.

**Comment by dstndstn** [comment]
Hi David,

Indeed, some layers do have this capability, though the limits might not be
set correctly!

--dstn

**Comment by sbailey** [comment]
OK, after @ziyaointl makes the fibers a separate layer, let's proceed with merging this PR and we can discuss ellipse math and optimizations for a future PR.  Ditto for tuning the "turn off layer X and zoom level Y" — let's tune that in separate tickets/PRs (or interactive hack session next week).

**Comment by ziyaointl** [comment]
Sounds good! I will try to get the new layer working before next week.

**Comment by ziyaointl** [comment]
I moved the fiber projections to a new layer.

Some food for thought: Although I think the code is fine as it is, there’s some room to improve code reusability, since `overlayAdded`, `load`, and `ready` methods of `DesiFiberPos` class and `DesiFootprint` class are the same. I don't know how to achieve this though. Maybe through some form of inheritance?

**Comment by dstndstn** [comment]
Thank you!

There is actually an inheritance system in play right now -- this is provided by the Leaflet code, and I know very little about it except the most basic syntax!

Notice that the `DesiFiberPos` inherits from `CatalogOverlay`, and the functions listed for it are only the ones it is subclassing:

`var DesiFiberPos = CatalogOverlay.extend({
...
});`

and currently, you have

`var DesiFootprint = CatalogOverlay.extend({`

but you could make them both inherit from a common class, or make one inherit from the other -- whatever makes sense to you!

We have a meeting of the DESI Imaging and Targeting group starting on Monday, and I would really like to have this feature merged in, because people will love this work!

I am perfectly happy merging this PR as is, but it seems like it won't take much work to add the inheritance structure you suggested.  If you can let me know if you will be able to do that in the next day or so, I will wait, and otherwise I'll just merge it and we can do any other fix-ups later!  (I believe in healthy work-life balance, don't expect people to work on weekends, etc!)

This is great work!

**Comment by ziyaointl** [comment]
Thanks, Dustin! I also believe in a healthy work-life balance, though I often can't help but deviate from this principle, esp. when the work is so engaging :) I will submit another commit by the end of today.

**Comment by dstndstn** [comment]
Awesome -- is this ready to go now?

**Comment by ziyaointl** [comment]
> Awesome -- is this ready to go now?

There's one small bug that I just realized. Shouldn't take too long to fix

**Comment by dstndstn** [comment]
Cool, just leave a comment when you're ready.

**Comment by ziyaointl** [comment]
After reading the code some more I realized the bug was inadvertently fixed by a previous commit. So yes, this should be ready to go!

**Comment by dstndstn** [comment]
Thank you again!  This is now live at http://legacysurvey.org/viewer-dev

**Comment by ziyaointl** [comment]
@dstndstn You are welcome! Thanks for all the insightful advice along the way!

**Pull request merged**
