### PR TITLE
Fix target label display

### PR DESCRIPTION
**Pull request by ziyaointl**
This is a simple fix to address issue #36

### CODE REVIEW

**Comment by ziyaointl** [comment]
BTW I feel like this is a little hacky, since `desinames` list can have only one item, whereas `bgsnames` and `mwsnames` can have more than one. That being said, this fix does seem to work and is quite simple. Feel free to chime in if anyone has better ideas!

**Comment by dstndstn** [comment]
Ahh, sorry for not explaining the problem better!  Some targets can actually have, say, both QSO and LRG bits set, or QSO and ELG.  They're not mutually exclusive, and targets that have more than one of those top-level bits are important to know about.

Maybe the simplest implementation would be a "veto" dictionary -- if you have bit ELG, remove the ELG_NORTH and ELG_SOUTH bits, and similarly for QSO, LRG, etc.

**Comment by ziyaointl** [comment]
Hi Dustin,

Thanks for the input! I came up with two slightly different approaches. The first approach utilizes a veto dictionary. It handles more cases than the second approach: e.g. we can now filter out 'BGS_ANY' if any of the other BGS names exist.
```python
# If any of the names in value exists, remove the key in bitnames
# Example: if 'BGS_FAINT' exists, remove 'BGS_ANY'
bitnames_veto = {
    'ELG_SOUTH': ['ELG'],
    'ELG_NORTH': ['ELG'],
    'QSO_SOUTH': ['QSO'],
    'QSO_NORTH': ['QSO'],
    'LRG_NORTH': ['LRG'],
    'LRG_SOUTH': ['LRG'],
    'BGS_FAINT_NORTH': ['BGS_FAINT'],
    'BGS_FAINT_SOUTH': ['BGS_FAINT'],
    'BGS_BRIGHT_NORTH': ['BGS_BRIGHT'],
    'BGS_BRIGHT_SOUTH': ['BGS_BRIGHT'],
    'BGS_ANY': ['BGS_FAINT', 'BGS_BRIGHT', 'BGS_FAINT_NORTH',
                'BGS_BRIGHT_NORTH', 'BGS_FAINT_SOUTH', 'BGS_BRIGHT_SOUTH',
                'BGS_KNOWN_ANY', 'BGS_KNOWN_COLLIDED', 'BGS_KNOWN_SDSS',
                'BGS_KNOWN_BOSS'],
    'MWS_ANY': ['MWS_MAIN', 'MWS_WD', 'MWS_NEARBY', 'MWS_MAIN_VERY_FAINT'],
}
for name in bitnames[:]:
    if any([better_name in bitnames for better_name in bitnames_veto.get(name, [])]):
        bitnames.remove(name)
```
The second approach is simpler. It loops through the names while removing other names that has it as their prefix. This approach can handling thing like ELGs, but it won't work for things like BGS_ANY.
```python
for name in bitnames[:]:
    bitnames = filter(lambda x: x == name or not x.startswith(name), bitnames)
    bitnames = list(bitnames)
```
Please let me know which one you would prefer, and I will commit the corresponding version. Thanks!

**Comment by dstndstn** [comment]
Hi Mark,
Awesome!  I think the more general veto version will be handy for other features we might want to add later.  Go with that one?

**Comment by ziyaointl** [comment]
Sounds good! I just committed the changes

**Comment by dstndstn** [comment]
It's live!

**Pull request merged**
