### PR TITLE
Limit the size of external uploads (Fixes #42)

### LINKED ISSUE #42: Limit the size of external uploads
As of now external uploads can get arbitrarily large depending on bandwidth within a timeout. Would be nice to instantiate a hard limit on the backend to prevent us from running out of disk space.

P.S. to @dstndstn , if you are busy with dr8 stuff, I'm happy to look into solutions and put together a pull request.

### PR DESCRIPTION
**Pull request by ziyaointl**

### CODE REVIEW

**Comment by ziyaointl** [comment]
Looks like the ref to #42 isn't recognized in the title...

**Comment by ziyaointl** [comment]
This isn't the most straightforward solution, but it's working (sort of). When I tested it on the development server, when the RuntimeError was thrown, used disk size on the server stopped increasing but the client kept uploading. I also tried raising StopUpload(connection_reset=True), but the same thing happens without me being able to catch the exception (Django has caught it instead).

Looks like this is a known bug (that is 10 years old!): https://code.djangoproject.com/ticket/10850

Therefore, it seems to me that limiting file size in the web server config is the easiest solution, though this pull request does provide another safeguard against large files.

**Comment by dstndstn** [comment]
Hi Mark,

Should we also change the UWSGI setting?  Note that we get to choose the uwsgi settings -- in uwsgi.sh and uwsgi-dev.sh -- so should we try setting the "--limit-post" option?

(I guess I might have to do this, because the uwsgi process is running as me on the sgn04 web server.)

--dustin

**Comment by ziyaointl** [comment]
Yeah changing the uwsgi setting sounds good. If this is sufficient, I’m now
tempted to scrape what I was proposing to make sure there’s one source of
truth for the max upload setting :) Could you change the setting on the dev
server? I can test it afterwards.

**Comment by dstndstn** [comment]
Hi Mark,

Sorry for my delay on this -- I just added the --limit-post option and restarted the dev version of the uwsgi server -- would you be able to test?

https://github.com/legacysurvey/decals-web/blob/master/uwsgi-dev.sh#L33

**Comment by ziyaointl** [comment]
No worries! I tested it out and the options seems to be working.
A file of size 40M successfully uploads on the client side and gets passed to Django.
A file of size 100M successfully uploads on the client side, but receives a 'Service Temporarily Unavailable' from Apache.
A file of size 1000M is stopped at ~35% and receives a 'Service Temporarily Unavailable' from Apache.

The only downside I could imagine to this method is that the user doesn't get a useful output when their legitimate catalog exceeds 50M, but usual catalogs don't go up to this size, so we should be fine?

**Comment by dstndstn** [comment]
Okay, that seems fine.

**Pull request closed without merging**
