### PR TITLE
Add DESI tile ID support

### PR DESCRIPTION
**Pull request by ziyaointl**
Automatically jump to a location given DESI tile ID.

Usage:
1. Using url query parameters. (e.g. http://127.0.0.1:8000/?desi_tile=1000)
2. Using Jump To Object text box located on the lower left. (e.g. type in DESI 1000 and hit enter). Redirects the user to the corresponding location and automatically turns on DESI Footprint and Fiber layers.

A few lingering questions:
1. Data file is current committed to git (in data/desi-tiles.fits). I noticed no data files in this directory exist in git before, so maybe I should remove it?
2. I put the query functions `get_desi_tile_radec` and `get_desi_tiles` in map/cats.py. Is this appropriate?
3. Right now every time `get_desi_tiles` gets called the server reads a 2.1 MB file from the disk. Should I introduce a caching mechanism?

Thanks!

### CODE REVIEW

**Comment by dstndstn** [comment]
Sorry for being so slow on this one!

1. Right, we haven't checked in most of the data files, because many are too big to comfortably live on github.  Could I ask you to try removing that file in a way that it doesn't stay in the git history?  I like to try to keep the git repository size down if possible.

2. map/cats.py is a good place for this. (At least, it matches what's there already; but it could use a cleanup and reorg!!)

3. Sure, a caching mechanism would be nice.  I often just use a global variable, initially set to None, and save the data values there.

Thanks for this -- it's a great idea and will be very useful.

**Comment by ziyaointl** [comment]
Hi Dustin,

I just removed the data file via a force push. I will proceed to implement caching.

Cheers,
Mark

**Comment by ziyaointl** [comment]
I was writing my own caching function using `django.core.cache` when I discovered `functools.lru_cache`. This ended up being a one-liner.

**Comment by ziyaointl** [comment]
Also, no worries if you need some time to reply! I understand that DR8 has a higher priority for now.

Cheers,
Mark

**Comment by dstndstn** [comment]
Cool!

btw: astropy.table is fine; elsewhere we use "from astrometry.util.fits import fits_table"; search around and you'll see lots of it.  Has a slightly more pythonic interface, if you ask me :).  Either way, no big deal.

**Comment by ziyaointl** [comment]
Thanks! I just briefly looked into the possibility of switching to astrometry.util.fits but the there seems to be some non-trivial changes needed to adapt to its API. I think I will leave the code as-is and remove the comment.

Mark

**Comment by dstndstn** [comment]
I think using astrometry.util.fits would be a matter of changing:

```
    t = Table.read(path)
    tileradec = dict()
    for tileid, ra, dec in t['TILEID', 'RA', 'DEC']:
        tileradec[tileid] = (ra,dec)
```

to

```
    t = fits_table(path)
    tileradec = dict()
    for tileid, ra, dec in zip(t.tileid, t.ra, t.dec):
        tileradec[tileid] = (ra,dec)
```

**Comment by ziyaointl** [comment]
Ah I forgot about the `zip(t.tileid, t.ra, t.dec)` syntax. Great idea to use it here. Committed!

**Comment by dstndstn** [comment]
Could you please send me (or tell me where on NERSC I can find) the desi-tiles.fits file?  Would like to deploy this!

**Comment by ziyaointl** [comment]
Sure! Sent via email

**Comment by dstndstn** [comment]
This is live now and looking great!

Would you consider adding the cool "Jump to object" search box shortcut for "brick" like you did for "DESI'?  Bricks are the regions of sky that we do the image processing on, and are named like 2345p678, for RA=234.5, Dec=+67.8  (p = "plus", and m = "minus").  It already handles &brick=2345p678 in the URL, but it would be nice to also have it work in the search box.

**Comment by ziyaointl** [comment]
Sure! I will try to get it done by the end of this week.

**Comment by dstndstn** [comment]
@sbailey might have other priorities for you :)  But I think it shouldn't be too much work, given what you have already figured out!

**Pull request merged**
