### PR TITLE
new Tan WCS prescription intended to work correctly at nonzero Dec

### PR DESCRIPTION
**Pull request by ameisner**
Hi Dustin,

I've created a pull request where I've attempted to replace the JavaScript variable containing the CI WCS parameters with the new parameters that I derived by treating all CI cameras as part of a common tangent plane. Hopefully there are no syntax/transcription errors here that ruin everything. I am happy to test this out if you can deploy it for me. Thanks very much.

-Aaron

### CODE REVIEW

**Comment by dstndstn** [comment]
Hi Aaron,

I'm confused -- if all the CRVAL1,CRVAL2 values are the same, then don't all the CRPIX1,2 values have to be different?  It looks like all your CRPIX1 values are the same, and there are only two distinct CRPIX2 values.  I think I would have expected each of CRPIX1 and CRPIX2 to have three values ~1000, one very large, and one very small.

**Comment by ameisner** [comment]
The trick is that the CD matrices for each camera are very different. The offsets to the outlying cameras are accomplished via the one large CRPIX2 value, but the +Y pixel axis of each of these four outlying cameras is pointed in a different direction (CIE has +Y pointed to the west, CIN has +Y pointed south, CIS has +Y pointed north, and CIW has +Y pointed east).

I think the confusion is due to me saying "part of a common tangent plane", which may not be strictly speaking the right way to phrase it -- what I meant is that, for all cameras, my WCS solution is based on a tangent plane with tangent point at (telra, teldec).

-Aaron

**Comment by dstndstn** [comment]
aha, gotcha!

**Comment by dstndstn** [comment]
I loaded this in the (dev) viewer --

I loaded up the "DESI Footprint" overlay and it looks like the CIC, CIN, CIS and CIW views agree with the pink outlines in the viewer.  CIE looks a little bit off.  (I'm not claiming by any stretch that the pink outlines are correct!  Just noting that they look different.)

**Pull request merged**
